Gaido/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('support', views.support, name="support"),
    path('search', views.search, name="search"),
    path('denied', views.perm_denied, name="no_perm"),
]

def response_error_handler(request, exception=None):
    pass
    
handler404 = 'Gaido.views.page_not_found'
handler500 = 'Gaido.views.server_error'

GaidoMain/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("Gaido.urls", "main"), namespace='main')),
    path('blog/', include(("blog.urls", 'blog'), namespace='blog')),
    path('user/', include(("user_auth.urls", 'user_auth'), 
    namespace='user_auth')),
    path('docs/', include(("guidemain.urls", 'guidemain'), namespace='guidemain')),
    path('tinymce/', include('tinymce.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'Gaido.views.page_not_found'
handler500 = 'Gaido.views.server_error'

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.createPost, name="create"),
    path('post/<uuid:uuid>', views.blogpost, name="blogpost"),
    path('<uuid:uuid>/edit', views.editpost, name="editpost"),
    path('<uuid:uuid>/comment', views.comment, name="comment"),
]

guidemain/urls.py
from django.urls import path  

from . import views

# Write the urls here.
urlpatterns = [
    path('', views.index, name='full'),
    path('sorted', views.specficview, name="specific")
]

user_auth/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login', views.loginview, name="login"),
    path('signup', views.signupview, name="signup"),
    path('logout', views.logoutview, name="logout"),
]

Gaido/models.py
from django.db import models
from user_auth.models import User

# Create your models here.

Gaido/forms.py
from django import forms
from django.forms import ModelForm


# Define the forms here
class SearchBarForm(forms.Form):
    search = forms.CharField(label=' ',
        max_length=32,
        widget=forms.TextInput(
            attrs={'class': 'form-control ml-2', 'placeholder': 'Search in Gaido...'}
            )
        )

Gaido/views.py
import html2text

from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator

from blog.models import Blogpost, Type, Region
from user_auth.models import User

from .forms import SearchBarForm
from .utils import get_categories, get_regions

# Create your views here.
def index(request):
    return render(request, 'main/index.html', {
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm()
    })

def support(request):
    return render(request, 'main/support.html', {
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm(),
    })

def perm_denied(request):
    return render(request, 'misc/perm_denied.html', {
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm,
    })


def page_not_found(request, exception):
    response = render_to_response('misc/404.html', {}, context_instance = RequestContext(request))
    response.status_code = 404
    return response

def server_error(request):
    response = render(request, 'misc/500.html')
    response.status_code = 500
    return response


def search(request):
    # Context
    query = request.GET.get('search')
    query = query.strip().lower()
    body_posts = []
    
    # Search body algo 
    allposts = Blogpost.objects.all()
    for post in allposts:
        content_in_string = html2text.html2text(post.content)
        if query in content_in_string:
            body_posts.append(post)
        else: 
            pass

        
    posts = Blogpost.objects.filter(title__icontains=query, briefing__icontains=query).all()

    p = Paginator(posts, 10)
    p2 = Paginator(body_posts, 10)

    if request.GET.get('page'):
        page_number = request.GET.get('page')
    else:
        page_number = 1
    
    all_page_obj = p.page(page_number)
    body_page_obj = p2.page(page_number)

    if len(body_page_obj) > len(all_page_obj):
        page_obj = body_page_obj
    else:
        page_obj = all_page_obj

    return render(request, 'main/searchresults.html', {
        'all_page_obj': all_page_obj,
        'body_page_obj': body_page_obj,
        'page_obj': page_obj,
        'query': query,
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm
    })

Gaido/templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- Primary Meta Tags -->
<title>{% block title %}{% endblock %} | Gaido</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Gaido- A Japanese Tourism Guide">
<meta name="author" content="Albert Wang">
<meta name="description" content="Open Source Japanese Tourism Application that people can share thoughts on.">

<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

<!-- Fontawesome -->
<link type="text/css" href="{% static 'dist/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

<!-- Pixel CSS -->
<link type="text/css" href="{% static 'dist/css/pixel.css' %}" rel="stylesheet">

<!-- Optional CSS-->
<style>
{% block css %}
{% endblock %}
</style>
{% block js %}
{% endblock %}
</head>

<body>
<!-- Navigation bar-->
{% block navbar %}
{% endblock %}

{% block body %}
{% endblock %}

{% block footer %}
{% endblock %}

    <!-- Core -->
<script src="{% static 'dist/vendor/@popperjs/core/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'dist/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dist/vendor/headroom.js/dist/headroom.min.js' %}"></script>

<!-- Vendor JS -->
<script src="{% static 'dist/vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>
<script src="{% static 'dist/vendor/jarallax/dist/jarallax.min.js' %}"></script>
<script src="{% static 'dist/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
<script src="{% static 'dist/vendor/vivus/dist/vivus.min.js' %}"></script>
<script src="{% static 'dist/vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

<!-- Pixel JS -->
<script src="{% static 'dist/assets/js/pixel.js' %}"></script>

</body>

</html>

Gaido/templates/layout/layout.html
{% extends 'layout/base.html' %}
{% load static %}

{% block navbar %}
<header class="header-global bg-primary fixed-top">
<nav class="navbar navbar-transparent navbar-dark navbar-expand-lg navbar-theme-primary" id="navbar-main">
  <div class="container position-relative mt-2 mb-2">
    <a class="navbar-brand mr-lg-3" href="{% url 'main:index' %}"><img src="{% static 'dist/icon.png' %}" class="mr-6"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-collapse-header">
            <div class="row">
                <div class="col-6 collapse-brand">
                <img src="{% static 'dist/icon.png' %}">
                <h1 class="mr-3">Gaido</h1>
                </div>
                <div class="col-6 collapse-close">
                    <i class="fas fa-times" data-bs-toggle="collapse" role="button"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation"></i>
                </div>
            </div>
        </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'main:index' %}">Introduction</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:index' %}">Main</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="{% url 'guidemain:full' %}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Toggle Categories View">
            Detailed Guide
            <i class="fas fa-angle-down nav-link-arrow ml-2"></i>
          </a>
          <ul class="dropdown-menu dropdown-megamenu-md p-0" aria-labelledby="navbarDropdown">
            <div class="row g-0">
                <div class="col-lg-6 bg-dark d-none d-lg-block pr-0 mr-3">
                    <div class="px-3 py-3 text-center bg-teritary">
                      <div class="container px-1 bg-teritary">
                        <img src="{% static 'dist/assets/img/metro/tokyo-metro.png' %}" alt="Map of Japan">
                        <a href="{% url 'main:search' %}?search=metro" class="btn btn-outline-white animate-up-2 mb-2 mb-sm-0 mt-3">View the Japanese Metro System</a>
                        <a href="{% url 'guidemain:full' %}" class="btn btn-danger animate-up-2 mb-2 mb-sm-0 mt-3">Full Documentation</a>
                      </div>
                    </div>
                </div>
                <div class="col-3 px-1">
                  <div class="container">
                    <span class="text"><p> </p></span>
                    <span class="text px-3 py-2">Regions</span>
                  </div>
                    <li><hr class="dropdown-divider"></li>
                    {% for category in categories %}
                      <li><a class="dropdown-item" href="{% url 'guidemain:specific' %}?sortby={{category}}">{{ category }}</a></li>
                    {% endfor %}
                </div>
                <div class="col-3 px-1">
                  <div class="container">
                    <span class="text"><p> </p> </span>
                    <span class="text px-3 py-2">Activities</span>
                  </div>
                    <li><hr class="dropdown-divider"></li>
                    {% for region in regions %}
                    <li><a class="dropdown-item" href="{% url 'guidemain:specific' %}?sortby={{region}}">{{ region }}</a></li>
                    {% endfor %}
                </div>
            </div>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:support' %}" tabindex="-1">Support</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown d-none d-lg-block">
                    <a class="nav-link dropdown-toggle btn btn-info " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    My Account
                    <i class="fas fa-angle-down nav-link-arrow ml-2"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="#">Profile (Working- Progess)</a></li>
                        <li><a class="dropdown-item" href="#">Settings (Working-Progress</a></li>
                        <li class="dropdown-item"><a class="text" href="{% url 'user_auth:logout' %}">Logout</a>
                        </li>
                    </ul>
        </li>
        <li class="nav-item d-block d-lg-none">
          <a class="nav-link" href="{% url 'user_auth:logout' %}" tabindex="-1">Logout</a>
        </li>
        {% endif %}
      </ul>
      <ul class="flex-row list-style-none px-1 d-none d-lg-flex">
        <li class="px-1">
            <a href="https://www.facebook.com/" target="_blank" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Like us on Facebook">
            <i class="fab fa-facebook text-white"></i>
            </a>
        </li>
        <li class="px-1">
            <a href="https://twitter.com/alb33rt_" target="_blank" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Follow us on Twitter">
            <i class="fab fa-twitter text-white"></i>
            </a>
        </li>
        <li class="px-1">
            <a href="https://github.com/alb33rt" target="_blank" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Star us on Github">
            <i class="fab fa-github text-white"></i>
            </a>
        </li>
    </ul>
    <form class="d-flex" action="{% url 'main:search' %}" method="GET">
        {% csrf_token %}
        {{ searchform }}
        <div class="ml-2">
          <button class="btn btn-outline-success px-3 ml-3" type="submit">Search</button>
        </div>
    </form>
    {% if request.user.is_authenticated %}
    {% else %}
    <a class="btn px-4 mt-4 mt-lg-0 btn-danger animate-up-2 logbutton" type="button" href="{% url 'user_auth:login' %}">Log in</a>
    {% endif %}
    </div>
  </div>
</nav>
</header>
{% endblock %}

{% block footer %}
<footer class="footer section section-sm bg-white text-gray">
    <div class="container">
        <div class="row align-items-md-center">
            <div class="col-md-4 mb-4 mb-md-0">
                <div class="d-flex align-items-center">
                <p class="small mb-0">© Gaido 2021.<br>All rights reserved.</p>
            </div>
        </div>
        <div class="col-sm-6 col-md-4 mb-4 mb-sm-0">
            <ul class="list-inline list-group-flush list-group-borderless text-md-center mb-0">
                <li class="list-inline-item px-0 px-sm-2">
                    <a class="text-gray" href="{% url 'main:index' %}">Start</a>
                </li>
                <li class="list-inline-item px-0 px-sm-2">
                    <a class="text-gray" href="{% url 'main:support' %}">Support</a>
                </li>
                <li class="list-inline-item px-0 px-sm-2">
                    <a class="text-gray" href="{% url 'blog:create' %}">Editor</a>
                </li>
            </ul>
        </div>
        <div class="col-sm-6 col-md-4">
                <ul class="list-inline text-sm-right mb-0">
                    <li class="list-inline-item">
                        <a class="icon icon-xs icon-twitter mr-3" href="https://www.twitter.com/alb33rt">
                            <span class="fab fa-twitter">
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="icon icon-xs icon-facebook mr-3" href="https://www.facebook.com/">
                            <span class="fab fa-facebook-f"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="icon icon-xs icon-github mr-3" href="https://www.github.com/alb33rt">
                        <span class="fab fa-github">
                        </span>
                        </a>
                    </li>
                </ul>
        </div>
    </div>
</footer>
{% endblock %}

Gaido/templates/layout/layouts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- Primary Meta Tags -->
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Gaido- A Japanese Tourism Guide">
<meta name="author" content="Albert Wang">
<meta name="description" content="Open Source Japanese Tourism Application that people can share thoughts on.">


<!-- Fontawesome -->
<link type="text/css" href="{% static 'dist/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

<!-- Pixel CSS -->
<link type="text/css" href="{% static 'dist/css/pixel.css' %}" rel="stylesheet">

<!-- Optional CSS-->
{% block css %}
{% endblock %}
</head>

<body>
<!-- Navigation bar-->
<header>
<nav class="navbar navbar-transparent navbar-dark navbar-expand-lg navbar-theme-primary bg-dark .headroom">
  <div class="container">
    <a class="navbar-brand" href="{% url 'main:index' %}">Gaido</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-collapse-header">
            <div class="row">
                <div class="col-6 collapse-brand">
                <h1 class="mr-3">Gaido</h1>
                </div>
                <div class="col-6 collapse-close">
                    <i class="fas fa-times" data-bs-toggle="collapse" role="button"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation"></i>
                </div>
            </div>
        </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'main:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Toggle Categories View">
            Categories
            <i class="fas fa-angle-down nav-link-arrow ml-2"></i>
          </a>
          <ul class="dropdown-menu dropdown-megamenu-md p-0" aria-labelledby="navbarDropdown">
            <div class="row g-0">
                <div class="col-lg-6 bg-dark d-none d-lg-block pr-0 mr-3">
                    <div class="px-3 py-3 text-center">
                      <div class="container px-5">
                        <img src="{% static 'dist\assets\img\japan\japanicon1.png' %}" alt="Map of Japan">
                      </div>
                    </div>
                </div>
                <div class="col-3 px-1">
                  <div class="container">
                    <span class="text"><p> </p></span>
                    <span class="text px-3 py-2">Regions</span>
                  </div>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Hokkaido</a></li>
                    <li><a class="dropdown-item" href="#">Kanto</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Nagoya</a></li>
                    <li><a class="dropdown-item" href="#">Kansai</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Shikouku</a></li>
                    <li><a class="dropdown-item" href="#">Kyushyu</a></li>
                </div>
                <div class="col-3 px-1">
                  <div class="container">
                    <span class="text"><p> </p> </span>
                    <span class="text px-3 py-2">Activities</span>
                  </div>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Anime</a></li>
                    <li><a class="dropdown-item" href="#">Food</a></li>
                    <li><a class="dropdown-item" href="#">Entertainment</a></li>
                    <li><a class="dropdown-item" href="#">Sports</a></li>
                    <li><a class="dropdown-item" href="#">History</a></li>
                    <li><a class="dropdown-item" href="#">Business</a></li>
                </div>
            </div>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" tabindex="-1">Support</a>
        </li>
      </ul>
      <ul class="flex-row list-style-none px-3 d-none d-lg-flex">
        <li class="px-1">
            <a href="https://www.facebook.com/" target="_blank" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Like us on Facebook">
            <i class="fab fa-facebook text-white"></i>
            </a>
        </li>
        <li class="px-1">
            <a href="https://twitter.com/" target="_blank" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Follow us on Twitter">
            <i class="fab fa-twitter text-white"></i>
            </a>
        </li>
        <li class="px-1">
            <a href="https://github.com/" target="_blank" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Star us on Github">
            <i class="fab fa-github text-white"></i>
            </a>
        </li>
    </ul>
    <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search in Guide..." aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    </div>
  </div>
</nav>
</header>

{% block body %}
{% endblock %}

    <!-- Core -->
<script src="{% static 'dist/vendor/@popperjs/core/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'dist/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dist/vendor/headroom.js/dist/headroom.min.js' %}"></script>

<!-- Vendor JS -->
<script src="{% static 'dist/vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>
<script src="{% static 'dist/vendor/jarallax/dist/jarallax.min.js' %}"></script>
<script src="{% static 'dist/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
<script src="{% static 'dist/vendor/vivus/dist/vivus.min.js' %}"></script>
<script src="{% static 'dist/vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

<!-- Pixel JS -->
<script src="{% static 'dist/assets/js/pixel.js' %}"></script>

</body>

</html>