Gaido/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('support', views.support, name="support"),
    path('search', views.search, name="search"),
    path('denied', views.perm_denied, name="no_perm"),
]

def response_error_handler(request, exception=None):
    pass
    
handler404 = 'Gaido.views.page_not_found'
handler500 = 'Gaido.views.server_error'

GaidoMain/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("Gaido.urls", "main"), namespace='main')),
    path('blog/', include(("blog.urls", 'blog'), namespace='blog')),
    path('user/', include(("user_auth.urls", 'user_auth'), 
    namespace='user_auth')),
    path('docs/', include(("guidemain.urls", 'guidemain'), namespace='guidemain')),
    path('tinymce/', include('tinymce.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'Gaido.views.page_not_found'
handler500 = 'Gaido.views.server_error'

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.createPost, name="create"),
    path('post/<uuid:uuid>', views.blogpost, name="blogpost"),
    path('<uuid:uuid>/edit', views.editpost, name="editpost"),
    path('<uuid:uuid>/comment', views.comment, name="comment"),
]

guidemain/urls.py
from django.urls import path  

from . import views

# Write the urls here.
urlpatterns = [
    path('', views.index, name='full'),
    path('sorted', views.specficview, name="specific")
]

user_auth/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login', views.loginview, name="login"),
    path('signup', views.signupview, name="signup"),
    path('logout', views.logoutview, name="logout"),
]

blog/models.py
import uuid

from django.db import models
from tinymce import models as tinymce_fields

from user_auth.models import User

# Create your models here.

# The following are the categories that are able to be given to the blog post
class Region(models.Model):
    HOKKAIDO = "HO"
    TOHOKU = "TO"
    KANTO = "KT"
    CHUBU = "CU"
    KANSAI = "KS"
    CHUGOKU = "CG"
    SHIKOKU = "SK"
    KYUSHU = "KY"
    REGION_CHOICES = [
        (HOKKAIDO, "Hokkaido"),
        (TOHOKU, "Tohoku"),
        (KANTO, "Kanto"),
        (CHUBU, "Chubu"),
        (KANSAI, "Kansai"),
        (CHUGOKU, "Chugoku"),
        (SHIKOKU, "Shiokoku"),
        (KYUSHU, "Kyushu"),
    ]

    region = models.CharField(max_length=2, choices=REGION_CHOICES, default=KANTO, primary_key=True)

    def __str__(self):
        for choice in self.REGION_CHOICES:
            if choice[0] == self.region:
                return choice[1]

class Type(models.Model):
    GENERAL = "GEN"
    ENTERTAINMENT = "ENT"
    FOOD = "FOD"
    SPORTS = "SPT"
    BUSINESS = "BUS"
    LEGAL = "LGL"
    TIPS = "TIP"
    CHOICES = [
        (GENERAL, "General"),
        (ENTERTAINMENT, "Entertainment"),
        (FOOD, "Food"),
        (SPORTS, "Sports"),
        (BUSINESS, "Business"),
        (LEGAL, "Legal"),
        (TIPS, "Tips"),
    ]

    choice = models.CharField(max_length=3, choices=CHOICES, default=GENERAL, primary_key=True)

    def __str__(self):
        for choice in self.CHOICES:
            if choice[0] == self.choice:
                return choice[1]


class Blogpost(models.Model):
    # Fields for the model object
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blogposts")
    title = models.CharField(max_length=128)
    briefing = models.CharField(max_length=512)
    content = tinymce_fields.HTMLField()
    thumbnail = models.ImageField(upload_to='thumbnails/', null=True, blank=True)
    featured = models.BooleanField(default=False)
    must_view = models.BooleanField(default=False)
    
    related_posts = models.ManyToManyField('self' , blank=True)

    region = models.ForeignKey(Region, related_name="blogposts", on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Type, related_name="blogposts", on_delete=models.SET_NULL, null=True)

    ups = models.IntegerField(verbose_name="claps", default=0)

    time_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time_created']

    # Functions
    def get_author_photo(self, *args):
        return self.author.photo

    # String represntation in Editor
    def __str__(self):
        name = f"{self.title} by {self.author}"
        return name

    def get_related_post(self):
        title_of_post = f"{self.related_posts.title}"
        return title_of_post

class Comment(models.Model):
    user = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE, null= True, blank = True)
    content = models.TextField(max_length=2048)
    time_created = models.DateTimeField(auto_now_add= True)

    post = models.ForeignKey(Blogpost, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)

blog/forms.py
from django import forms
from django.forms import TextInput, SelectMultiple, Textarea, Select, URLInput, FileInput
from tinymce.widgets import TinyMCE

from .models import Blogpost, Comment

class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Blogpost
        # fields = ['title', 'briefing', 'content', 'thumbnail', 'region', 'category', 'related_posts']
        fields = ['title', 'briefing', 'content', 'thumbnail', 'region', 'category']

        labels= {
            'title': ('Title of Post'),
            'related_posts': ('Links to other posts'),
        }
        
        
        widgets = {
            'title': TextInput(attrs={'class': "form-control", 'size': 40, 'placeholder': "Enter the Title..."}),
            'briefing': Textarea(attrs={'class': "form-control", 'placeholder': "Enter the briefing..."}),
            'thumbnail': FileInput(attrs={'class': 'form-control', 'required': True}),
            'region': Select(attrs={'class': "form-control",}, ),
            'category':  Select(attrs={'class': "form-control",}, ),
            'related_posts': Select(attrs={'class': 'form-control', 'placeholder': "Insert Post..."}),
        }

class EditPostForm(CreatePostForm):
    thumbnail = forms.ImageField(disabled= True)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content'
        ]

        widgets = {
            'content': TextInput(attrs={'class': 'form-control', 'row': 2})
        }

blog/views.py
import uuid as a

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.core.exceptions import PermissionDenied

from user_auth.models import User
from Gaido.forms import SearchBarForm
from Gaido.utils import get_regions, get_categories

from .forms import CreatePostForm, EditPostForm, CommentForm
from .models import Blogpost, Comment
# Create your views here.
def index(request):
    posts = Blogpost.objects.all()
    featured_posts = Blogpost.objects.exclude(featured=False).all()
    p = Paginator(posts, 10)
    
    if request.GET.get('page'):
        page_number = request.GET.get('page')
    else:
        page_number = 1

    page_obj = p.page(page_number)

    for features in featured_posts:
        if features.thumbnail:
            imageurl = features.thumbnail.url
        
        else:
            imageurl = False

    return render(request, 'blog/index.html', {
        'featured_posts': featured_posts,
        'page_obj': page_obj,
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm(),
    })

def authorperm(user):
    if user.has_perm('blog.add_blogpost'):
        pass
    else:
        return HttpResponseRedirect(reverse('main:no_perm'))

def createPost(request):
    authorperm(request.user)
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('main:no_perm'))
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        
        if form.is_valid():
            # Context
            title = form.cleaned_data.get('title')
            briefing = form.cleaned_data.get('briefing')
            content = form.cleaned_data['content']
            thumbnail = form.cleaned_data['thumbnail']
            category = form.cleaned_data['category']
            region = form.cleaned_data['region']
            uuid = a.uuid4()

            f = Blogpost(uuid=uuid, title=title, briefing=briefing, content=content, author=request.user, thumbnail=thumbnail, category=category, region=region)
            f.save()

            if f is None:
                return render(request, 'misc/500.html')

            return HttpResponseRedirect(reverse('blog:index'))
    
    else:
        form = CreatePostForm(initial={
            'region': 'Kanto',
            'category': 'General',
        })
        return render(request, 'blog/create.html', {
            'form': form,
            'categories': get_categories,
            'regions': get_regions,
            'searchform': SearchBarForm(),
        })

def blogpost(request, uuid):
    post = Blogpost.objects.filter(uuid=uuid).get()
    comments = Comment.objects.filter(post=post).all()

    author = post.author
    authorobject = User.objects.filter(username=author).first()
    return render(request, 'blog/blogpost.html', {
        'post': post,
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm(),
        'author': authorobject,
        'commentform': CommentForm(),
        'comments': comments,
    })

def editpost(request, uuid):
    authorperm(request.user)

    if request.method == "POST":
        if uuid:
            post = get_object_or_404(Blogpost, uuid=uuid)
            if request.user != post.author:
                return render(request, 'misc/perm_denied.html')
            else: 
                pass
        
        # code that updates the blogpost
        form = EditPostForm(request.POST, instance=post)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            briefing = form.cleaned_data.get('briefing')
            content = form.cleaned_data['content']
            category = form.cleaned_data['category']
            region = form.cleaned_data['region']

            form.save(commit=True)
            return HttpResponseRedirect(reverse('blog:blogpost', args=[uuid]))
            
        else:
            return render(request, 'misc/500.html')

    
    post = Blogpost.objects.filter(uuid=uuid).get()
    if post.related_posts:
        form = CreatePostForm(initial={
            'title': post.title,
            'content': post.content,
            'briefing': post.briefing,
            'category': post.category,
            'region': post.region,
            'related_posts': post.related_posts,
        })
    else:
        form = CreatePostForm(initial={
            'title': post.title,
            'content': post.content,
            'briefing': post.briefing,
            'category': post.category,
            'region': post.region,
        })


    return render(request, 'blog/edit.html', {
        'form': form,
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm(),
        'uuid': post.uuid
    })


def comment(request, uuid):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            user = request.user
            post = Blogpost.objects.filter(uuid=uuid).get()

            if (content.strip() == ""):
                message = "Please do not enter empty in comments."
                messages.error = (request, message)
                return HttpResponseRedirect(reverse('blog:blogpost', args=[uuid]))
            
            newcomment = Comment(user=user, content=content, post=post)
            newcomment.save()

            return HttpResponseRedirect(reverse('blog:blogpost', args=[uuid]))
    else:
        return render(request, 'misc/500.html')

blog/templates/blog/blogpost.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block css %}
@media screen and (min-width: 800px) {
    #thumbnail {
    margin-top: -200px !important;
    }   
}

#profilepic{
    border-radius:50% !important;
}

#aheader {
    margin-top:-420px;
    margin-bottom: 100px;
}

.section-header {
    background-image: url('{{ post.thumbnail.url }}') !important;
    background-size: cover;
    filter: brightness(50%);
    -webkit-filter: brightness(50%);

    height: 500px;

}


{% endblock %}

{% block body %}
<main>
<section class="section-header text-white align-items-center">
</section>
<section class="section text-white align-items-center" id="aheader">
    <div class="container" style="
    filter: brightness(100%);
    -webkit-filter: brightness(100%);
">
    <h1 class="display-2">
        {{ post.title }}
    </h1>
    <p class="text d-none d-lg-block"> 
        {{ post.briefing }}
    </p>
    <span class="h6 icon-tertiary small px-2"><i class="fas fa-pencil-ruler mr-2"></i> {{ post.category }}</span>
    <span class="h6 icon-tertiary small px-2"><i class="fas fa-map mr-2"></i>  {{ post.region }}</span>
    <p class="text mt-4">
    by {{ post.author }} <img src="{{ author.photo.url }}" alt="Image of Author" height="50px" id="profilepic">
    
    {% if request.user == post.author %}
    <a href="{% url 'blog:editpost' uuid=post.uuid %}" class="btn btn-danger">Edit Page</a>
    {% endif %}
    </div>
</section>
<section class="bg-white section text-dark align-items-center">
<div class="container">
    <div class="row">
    <div class="col-lg-8" width=100% id="thumbnail">
    <img src="{{ post.thumbnail.url }}">
    <p class="text mt-4">
    {{ post.content | safe }}
    <hr>
    Written {{ post.time_created | timesince }} ago
    </p>
    <div class="mt-6">
    <h3 class="display-4">Related Posts</h3>
    <hr>
    <a href="{{ post.related_posts }}">{{ post.get_related_posts }}</a>
    </div>
    </div>
    <div class="d-none d-lg-block col-lg-4 blog-sidebar ml-6">
        Navigation
        <hr>
        <div class="card bg-dark">
            <div class="container mt-4 bg-teritary align-items-center text-center">
                <img src="{% static 'dist/assets/img/metro/tokyo-metro.png' %}" alt="Map of Japan">
                <a href="{% url 'main:search' %}?search=metro" class="btn btn-outline-white animate-up-2 mb-2 mb-sm-0 mt-2">View the Japanese Metro System</a>
                <hr>
            </div>
        </div>
        <div class="card bg-white mt-4">
            <div class="container mt-4 bg-white align-items-center text-dark">
                <div class="nav-wrapper position-relative">
                    <ul class="nav nav-pills square nav-fill flex-column vertical-tab">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#"><span class="d-block"><i class="fas fa-dungeon mr-2"></i> Home</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="{% url 'guidemain:specific' %}?sortby=General"><span class="d-block"><i class="far fa-user-circle mr-2"></i> General</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="{% url 'guidemain:full' %}"><span class="d-block"><i class="far fa-sun mr-2"></i> Documentation</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="{% url 'main:support' %}"><span class="d-block"><i class="far fa-comments mr-2"></i> Apply for Author</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
<section class="bg-white justify-content-center align-items-center">
<div class="container">
    <h3 class="display-3">
    Comments
    </h3>
    <hr>
    {% if user.is_authenticated %}
    <form action="{% url 'blog:comment' uuid=post.uuid %}" method="POST">
        {% csrf_token %}
        {{ commentform }}
        <div class="mt-2">
        <input type="submit" name="submit" value="Post Comment" class="btn btn-danger">
        </div>
    </form>
    {% else %}
    <a href="{% url 'user_auth:login' %}" class="btn btn-danger">
    Log In to Comment
    </a>
    {% endif %}
    <div class="row d-none d-lg-block mt-3">
    <div class="col-8">
    {% for comment in comments %}
    <div class="card">
        <div class="card-body">
            <div class="col-3">
            </div>
            <div class="col-9">
                <p class="text">{{ comment.content }}</p>
                <small class="text-muted">{{ comment.time_created | timesince }} ago, by {{ comment.user | safe }}</small>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    </div>
</div>
</section>

</main>

{% endblock %}

blog/templates/blog/create.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block title %}
Create Post
{% endblock %}

{% block css %}
.main-form {
        margin-top: 150px !important;
    }
{% endblock %}

{% block body %}
<main>
<div class="container justify-content-left main-form">
    <div class="col">
        <div class="mt-4">
            <div class="row">
                <h1 class="display">Create an Post</h1>
                <div class="card">
                    <div class="card-body">
                    Guidelines:
                    <ul class="list">
                        <li class="card-text">Font size: 14px</li>
                        <li class="card-text">Image should be consistent</li>
                        <li class="card-text">Articles should not be overly prolonged</li>
                        <li class="card-text">Images must be wider than its height.</li>
                        <li class="card-text">Violation of any guideline will result in the article being taken down.</li>
                    </ul>
                </div>
            </div>
            <div class="row mt-3">
                {% comment %} Create Form {% endcomment %}
                <form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                    {{ form.media }}
                    <div class="d-block">
                     <div class="row mt-4">
                         <div class="col-lg-6">
                             <div class="mt-2">
                             Title:
                             {{ form.title }}
                             </div>
                             <div class="mt-2">
                             Category:
                             {{ form.category }}
                             </div>
                             <div class="mt-2">
                             Region:
                             {{ form.region }}
                             </div>
                         </div>
                         <div class="col-lg-6 mt-3">
                            Briefing / Summary:
                             {{ form.briefing }}
                         </div>
                     </div>
                     <div class="row mt-4">
                         <div class="col-lg-12">
                            <h3 class="display-4">Main Body:</h3>
                             {{ form.content }}
                             <small class="text-muted">You can drag the TinyMCE Editor down for a more extensive writing experience.</small>
                         </div>
                     </div>
                     <div class="row mt-4">
                         <div class="col-lg-6">
                             Thumbnail for Post:
                             {{ form.thumbnail }}
                         </div>
                         <div class="col-lg-6">
                             Related Links:
                             {{ form.related_posts }}
                         </div>
                     </div>
                    </div>
                    <input type="submit" class="btn btn-primary mt-4" value="Submit">
                </form>
            </div>

        </div>
    </div>
</div>
</main>
{% endblock %}

blog/templates/blog/index.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block title %}
Blogs
{% endblock %}

{% block css %}
@media screen and (min-width: 800px) {
    #featuredpost {
        margin-top: -250px !important;
    }
}

@media screen and (min-width: 0px) {
    #featuredpost {
        margin-top: -300px !important;
    }
}

.card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
}
{% endblock %}

{% block body %}
<main>
<div class="bg-dark flex-column py-0">
<section class="section-header text-white" style="
    background-image: url('{% static 'dist/assets/img/japan/tokyo-skyview.jpg' %}');
    background-size: cover;

" height=100%>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 text-center">
        <h1 class="display-2 mb-4">Traveling in Japan</h1>
        <p class="lead">Traveling in Japan is extremely difficult without knowledge of the current circumstance. Use our blogs to take a look at life in Japan! <a href="#" class="text-muted">For more info on how the website is structured, click here.</a></p>
        </div>
    </div>
    <div class="row justify-content-center align-items-center mt-0 text-center text-danger">
    {% if request.user.is_superuser %}
        <div class="alert alert-danger mt-3" role="alert">
            <span class="alert-inner--text">Welcome back Admin User- <b>{{request.user}}</b>. To create a post:  
            <a href="{% url 'blog:create' %}" class="btn btn-danger px-2 py-2 animate-right-3 mb-1 mt-2 mt-lg-0"> go to the editor <span class="fas fa-arrow-right">
            </a></span>
        </div>
    {% elif request.user.is_authenticated %}
        <div class="alert alert-info mt-3 px-1" role="alert">
            <span class="alert-inner--text">You are currently logged in. Welcome back <b>{{ request.user }}.</b></span>
        </div>
    {% else %}
    {% endif %}
    </div>
    <span class="display-4 mt-6">Latest News</span>
    <hr>
</div>
</section>
<section class="section section-lg line-bottom-light bg-white" height=100%>
    <div class="container" id="featuredpost">
        <div class="row mb-5">
            {% for features in featured_posts %}
            <div class="col-12 col-sm-11 col-xl-6 mb-5 mb-lg-0">
                <div class="card border-light">
                    {% if features.thumbnail %}
                    <img src="{{ features.thumbnail.url }}" class="card-img-top rounded-top" alt="image">
                    {% else %}
                    <img src="#" class="card-img-top rounded-top" alt="image">
                    {% endif %}
                    <div class="card-body">
                        <span class="h6 icon-tertiary small"><i class="fas fa-medal mr-2"></i>Top Featured</span>
                        <h5 class="card-title mt-3">{{ features.title }}</h5>
                        <p class="card-text">{{ features.briefing | safe }}</p>
                        <a href="{% url 'blog:blogpost' features.uuid %}" class="btn btn-primary btn-sm px-2"> Read More </a>
                        
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="container mt-0">
        <div class="row justify-content-center">
            <div class="col-lg-8 blog-main">
                <div class="container">
                    <!-- Header -->
                    <span class="display-4">
                    From Gaido 
                    <hr>
                    </span>

                    <!-- Main Content BLocks -->
                    {% for post in page_obj %}
                    <div class="row mt-2">
                        <div class="col-12 mb-5 mb-lg-0">
                            <div class="card border-light">
                                <div class="row no-gutters align-items-center">
                                    <div class="col-md-4">
                                    <a href="{% url 'blog:blogpost' post.uuid %}" class="card-img">
                                    {% if post.thumbnail %}
                                        <img src="{{ post.thumbnail.url }}" class="card-img card-img-top rounded-left" alt="image" height=100%>
                                    {% else %}
                                        <img src="#" class="card-img rounded-left" alt="image" height=100%>
                                    {% endif %}
                                    </a>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <a href="{% url 'blog:blogpost' post.uuid %}"><h5 class="card-title">
                                            {{ post.title }}</h5></a>
                                            <span class="h6 icon-tertiary small mb-2"><i class="fas fa-pencil-ruler px-2 py-2"></i>{{ post.category }}</span>
                                            <p class="card-text mb-4">{{ post.briefing }}</p>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <span class="card-text small"><i class="far fa-calendar-alt mr-2"></i> Posted {{ post.time_created | timesince }} ago</span>
                                                <a href="{% url 'blog:blogpost' uuid=post.uuid %}" class="small"><i class="far fa-comments mr-2"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <nav aria-label="Page Navigation">
                        <ul class="pagination mt-3">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1"><i class="fas fa-angle-double-left"></i></a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                            </li>
                            {% endif %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ page_obj.number }}</a>
                            </li>
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"><i class="fas fa-angle-double-right"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="d-none d-lg-block col-lg-4 blog-sidebar">
                Navigation
                <hr>
                <div class="card bg-dark">
                    <div class="container mt-4 bg-teritary align-items-center text-center">
                        <img src="{% static 'dist/assets/img/metro/tokyo-metro.png' %}" alt="Map of Japan">
                        <a href="{% url 'main:search' %}?search=metro" class="btn btn-outline-white animate-up-2 mb-2 mb-sm-0 mt-2">View the Japanese Metro System</a>
                        <hr>
                    </div>
                </div>
                <div class="card bg-white mt-4">
                    <div class="container mt-4 bg-white align-items-center text-dark">
                        <div class="nav-wrapper position-relative">
                            <ul class="nav nav-pills square nav-fill flex-column vertical-tab">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#"><span class="d-block"><i class="fas fa-dungeon mr-2"></i> Home</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="{% url 'guidemain:specific' %}?sortby=General"><span class="d-block"><i class="far fa-user-circle mr-2"></i> General</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="{% url 'guidemain:full' %}"><span class="d-block"><i class="far fa-sun mr-2"></i> Documentation</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="{% url 'main:support' %}"><span class="d-block"><i class="far fa-comments mr-2"></i> Apply for Author</span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
        </div> 
    </div>
</section>
</div>


</main>
{% endblock %}