Gaido/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('support', views.support, name="support"),
    path('search', views.search, name="search"),
    path('denied', views.perm_denied, name="no_perm"),
]

def response_error_handler(request, exception=None):
    pass
    
handler404 = 'Gaido.views.page_not_found'
handler500 = 'Gaido.views.server_error'

GaidoMain/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("Gaido.urls", "main"), namespace='main')),
    path('blog/', include(("blog.urls", 'blog'), namespace='blog')),
    path('user/', include(("user_auth.urls", 'user_auth'), 
    namespace='user_auth')),
    path('docs/', include(("guidemain.urls", 'guidemain'), namespace='guidemain')),
    path('tinymce/', include('tinymce.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'Gaido.views.page_not_found'
handler500 = 'Gaido.views.server_error'

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.createPost, name="create"),
    path('post/<uuid:uuid>', views.blogpost, name="blogpost"),
    path('<uuid:uuid>/edit', views.editpost, name="editpost"),
    path('<uuid:uuid>/comment', views.comment, name="comment"),
]

guidemain/urls.py
from django.urls import path  

from . import views

# Write the urls here.
urlpatterns = [
    path('', views.index, name='full'),
    path('sorted', views.specficview, name="specific")
]

Gaido/models.py
from django.db import models
from user_auth.models import User

# Create your models here.

Gaido/forms.py
from django import forms
from django.forms import ModelForm


# Define the forms here
class SearchBarForm(forms.Form):
    search = forms.CharField(label=' ',
        max_length=32,
        widget=forms.TextInput(
            attrs={'class': 'form-control ml-2', 'placeholder': 'Search in Gaido...'}
            )
        )

Gaido/views.py
import html2text

from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator

from blog.models import Blogpost, Type, Region
from user_auth.models import User

from .forms import SearchBarForm
from .utils import get_categories, get_regions

# Create your views here.
def index(request):
    return render(request, 'main/index.html', {
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm()
    })

def support(request):
    return render(request, 'main/support.html', {
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm(),
    })

def perm_denied(request):
    return render(request, 'misc/perm_denied.html', {
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm,
    })


def page_not_found(request, exception):
    response = render_to_response('misc/404.html', {}, context_instance = RequestContext(request))
    response.status_code = 404
    return response

def server_error(request):
    response = render(request, 'misc/500.html')
    response.status_code = 500
    return response


def search(request):
    # Context
    query = request.GET.get('search')
    query = query.strip().lower()
    body_posts = []
    
    # Search body algo 
    allposts = Blogpost.objects.all()
    for post in allposts:
        content_in_string = html2text.html2text(post.content)
        if query in content_in_string:
            body_posts.append(post)
        else: 
            pass

        
    posts = Blogpost.objects.filter(title__icontains=query, briefing__icontains=query).all()

    p = Paginator(posts, 10)
    p2 = Paginator(body_posts, 10)

    if request.GET.get('page'):
        page_number = request.GET.get('page')
    else:
        page_number = 1
    
    all_page_obj = p.page(page_number)
    body_page_obj = p2.page(page_number)

    if len(body_page_obj) > len(all_page_obj):
        page_obj = body_page_obj
    else:
        page_obj = all_page_obj

    return render(request, 'main/searchresults.html', {
        'all_page_obj': all_page_obj,
        'body_page_obj': body_page_obj,
        'page_obj': page_obj,
        'query': query,
        'categories': get_categories,
        'regions': get_regions,
        'searchform': SearchBarForm
    })

Gaido/templates/main/index.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block title %}
Start
{% endblock %}

{% block body %}
<div class="preloader bg-dark flex-column justify-content-center align-items-center">
    <svg id="loader-logo" xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 64 78.4">
        <path fill="#fff" d="M10,0h1.2V11.2H0V10A10,10,0,0,1,10,0Z"/>
        <rect fill="none" stroke="#fff" stroke-width="11.2" x="40" y="17.6" width="0" height="25.6"/>
        <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="11.2" x="23" y="35.2" width="0" height="25.6"/>
        <path fill="#fff" d="M52.8,35.2H64V53.8a7,7,0,0,1-7,7H52.8V35.2Z"/>
        <rect fill="none" stroke="#fff" stroke-width="11.2" x="6" y="52.8" width="0" height="25.6"/>
        <path fill="#fff" d="M52.8,0H57a7,7,0,0,1,7,7h0v4.2H52.8V0Z"/>
        <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="11.2" x="57.8" y="17.6" width="0" height="11.2"/>
        <rect fill="none" stroke="#fff" stroke-width="11.2" x="6" y="35.2" width="0" height="11.2"/>
        <rect fill="none" stroke="#fff" stroke-width="11.2" x="40.2" y="49.6" width="0" height="11.2"/>
        <path fill="#fff" d="M17.6,67.2H28.8v1.2a10,10,0,0,1-10,10H17.6V67.2Z"/>
        <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="28.8" x="31.6" width="0" height="11.2"/>
        <rect fill="none" stroke="#fff" x="14" stroke-width="28.8" y="17.6" width="0" height="11.2"/>
    </svg>
</div>
<main>
    <div class="container mt-6">
        <!-- Title Of the Page-->
        <div class="row justify-content-between align-items-center">
            <div class="col-12 col-md-7 col-lg-6 text-center text-md-left">
                <h1 class="display-2 text-center mt-6">Gaido</h1>
                <p class="lead text-center">A Japanese Tourism Guide that explains everything.</p>
                <p class="lead text-center">Powered by the internet and open source.</p>
                <div class="justify-content-center text-center">
                <a href="{% url 'blog:index' %}" class="btn btn-teritary me-3 animate-right-6">Full Guide Click Here<span class="ms-2"><span class="fas fa-arrow-right"></a>
                </div>
            </div>
            <div class="col-md-5 col-lg-6 mt-6 mr-5">
                <img src="{% static 'dist/assets/img/japan/japandiagram.jpg' %}">
            </div>
        </div>
        <section class="section section-md">
            <div class="container">
                <div class="row align-items-center justify-content-around">
                    <div class="col-md-6 col-xl-6 mb-5">
                        <img class="organic-radius img-fluid" src="{% static 'dist/assets/img/japan/titletower.jpg' %}" alt="Office Desk">
                    </div>
                    <div class="col-md-6 col-xl-5 text-center text-md-left">
                        <h2 class="h1 mb-5">Free Source Contribution</h2>
                        <p class="lead">Gaido is open for anyone to apply as a position to write for the guide. The application process is tough and requires extensive knowledge of Japan.</p>
                        <p class="lead">With a culture of collaboration, a roster of talent, and unique online prescence. Gaido promises to give the best all-around Japan travel documentation Guide.</p>
                        <div class="row">
                        <span class="text-muted">Albert- Creator of Gaido</span>
                        </div>
                        <div class="row">
                        <span class="text-muted mt-5">Photo from Unsplash</span>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock %}

Gaido/templates/main/searchresults.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block title %}
Search Results
{% endblock %}

{% block css %}
@media screen and (min-width: 800px) {
    #featuredpost {
        margin-top: -250px !important;
    }
}

@media screen and (min-width: 0px) {
    #featuredpost {
        margin-top: -300px !important;
    }
}
{% endblock %}

{% block body %}
<main>
<div class="bg-dark flex-column py-0">
<section class="section-header text-white" style="
    background-image: url('{% static 'dist/assets/img/japan/tokyo-skyview.jpg' %}');
    background-size: cover;

" height=100%>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 text-center">
        <h1 class="display-2 mb-4">Search Results</h1>
        <hr>
        </div>
    </div>
    <div class="row justify-content-center align-items-center mt-0 text-center text-danger">
    {% if user.is_superuser %}
        <div class="alert alert-danger mt-3" role="alert">
            <span class="alert-inner--text">Welcome back Admin User- <b>{{request.user}}</b>. To create a post:  
            <a href="{% url 'blog:create' %}" class="btn btn-danger px-2 py-2 animate-right-3 mb-1 mt-2 mt-lg-0"> go to the editor <span class="fas fa-arrow-right">
            </a></span>
        </div>
    {% elif user.is_authenticated %}
        <div class="alert alert-info mt-3 px-1" role="alert">
            <span class="alert-inner--text">You are currently logged in. Welcome back <b>{{ request.user }}.</b></span>
        </div>
    {% else %}
    {% endif %}
</div>
</section>
<section class="section section-lg line-bottom-light bg-white" height=100%>
    <div class="container mt-0">
        <div class="row justify-content-center">
            <div class="col-lg-8 blog-main">
                <div class="container">
                    <!-- Header -->
                    <span class="display-4">
                    Related Posts by Title and Summary
                    <hr>
                    </span>
                    {% if all_page_obj %}
                    <!-- Main Content BLocks -->
                    {% for post in all_page_obj %}
                    <div class="row mt-2">
                        <div class="col-12 mb-5 mb-lg-0">
                            <div class="card border-light">
                                <div class="row no-gutters align-items-center">
                                    <div class="col-md-4">
                                    <a href="{% url 'blog:blogpost' post.uuid %}" class="card-img">
                                        <img src="{{ post.thumbnail.url }}" class="card-img rounded-left" alt="image" height=100%>
                                    </a>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <a href="{% url 'blog:blogpost' post.uuid %}"><h5 class="card-title">
                                            {{ post.title }}</h5></a>
                                            <span class="h6 icon-tertiary small mb-2"><i class="fas fa-pencil-ruler px-2 py-2"></i>{{ post.category }}</span>
                                            <p class="card-text mb-4">{{ post.briefing }}</p>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <span class="card-text small"><i class="far fa-calendar-alt mr-2"></i>  {{ post.time_created }}</span>
                                                <a href="#" class="small"><i class="far fa-comments mr-2"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p class="text"> No Results </p>
                    {% endif %}
                    
                    <hr>
                    <!-- Header -->
                    <span class="display-4">
                    Related Posts by Body
                    <hr>
                    </span>

                    {% if body_page_obj %}
                    <!-- Main Content BLocks -->
                    {% for post in body_page_obj %}
                    <div class="row" id="">
                        <div class="col-12 mb-5 mb-lg-0">
                            <div class="card border-light">
                                <div class="row no-gutters align-items-center">
                                    <div class="col-md-4">
                                    <a href="{% url 'blog:blogpost' post.uuid %}" class="card-img">
                                        <img src="{{ post.thumbnail.url }}" class="card-img rounded-left" alt="image" height=100%>
                                    </a>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <a href="{% url 'blog:blogpost' post.uuid %}"><h5 class="card-title">
                                            {{ post.title }}</h5></a>
                                            <span class="h6 icon-tertiary small mb-2"><i class="fas fa-pencil-ruler px-2 py-2"></i>{{ post.category }}</span>
                                            <p class="card-text mb-4">{{ post.briefing }}</p>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <span class="card-text small"><i class="far fa-calendar-alt mr-2"></i>  {{ post.time_created }}</span>
                                                <a href="#" class="small"><i class="far fa-comments mr-2"></i>21</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p class="text"> No Results </p>
                    {% endif %}
                    <nav aria-label="Page Navigation">
                        <ul class="pagination mt-3">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1&search={{query}}"><i class="fas fa-angle-double-left"></i></a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{query}}">{{ page_obj.previous_page_number }}</a>
                            </li>
                            {% endif %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ page_obj.number }}</a>
                            </li>
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{query}}">{{ page_obj.next_page_number }}</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&search={{query}}"><i class="fas fa-angle-double-right"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="d-none d-lg-block col-lg-4 blog-sidebar">
                Navigation
                <hr>
                <div class="card bg-dark">
                    <div class="container mt-4 bg-teritary align-items-center text-center">
                        <img src="{% static 'dist/assets/img/metro/tokyo-metro.png' %}" alt="Map of Japan">
                        <a href="{% url 'main:search' %}?search=metro" class="btn btn-outline-white animate-up-2 mb-2 mb-sm-0 mt-2">View the Japanese Metro System</a>
                        <hr>
                    </div>
                </div>
                <div class="card bg-white mt-4">
                    <div class="card bg-white mt-4">
                    <div class="container mt-4 bg-white align-items-center text-dark">
                        <div class="nav-wrapper position-relative">
                            <ul class="nav nav-pills square nav-fill flex-column vertical-tab">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#"><span class="d-block"><i class="fas fa-dungeon mr-2"></i> Home</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="{% url 'guidemain:specific' %}?sortby=General"><span class="d-block"><i class="far fa-user-circle mr-3"></i>  General</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="{% url 'guidemain:full' %}"><span class="d-block"><i class="far fa-sun mr-2"></i> Documentation</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="{% url 'main:support' %}"><span class="d-block"><i class="far fa-comments mr-2"></i> Apply for Author</span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</section>
</div>


</main>
{% endblock %}

Gaido/templates/main/support.html
{% extends 'layout/layout.html' %}

{% block title %}
Support
{% endblock %}

{% block css %}
{% comment %} #map {
    margin-top: 200px;
    height: 400px !important;
    /* The height is 400 pixels */
    width: 100% !important;
    /* The width is the width of the web page */
}

{% endcomment %} 
#container {
    margin-top: 100px !important;
}
{% endblock %}

{% block js %}
{% comment %} <script>
function initMap() {
    // The location of Uluru
    const uluru = { lat: -25.344, lng: 131.036 };
    // The map, centered at Uluru
    const map = new google.maps.Map(document.getElementById("map"), {
        zoom: 4,
        center: taichung,
    });
    // The marker, positioned at Uluru
    const marker = new google.maps.Marker({
        position: taichung,
        map: map,
    });
}
</script> {% endcomment %}
{% endblock %}

{% block body %}
<main>
<div class="container">
<div id="container" class="row mt-4 mt-lg-6 align-items-center justify-content-between">
    <div class="col-12 col-lg-4 text-center">
        <div class="row">
            <div class="col-12 col-sm-6 col-lg-12"><div class="icon-box mb-5">
                <div class="icon icon-dark mb-4">
                <span class="fas fa-map-marker-alt"></span>
                </div>
                <h2 class="h5">Visit me</h2><span>Taichung<br>Taiwan, Asia</span>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-lg-12">
            <div class="icon-box mb-4">
                <div class="icon icon-dark mb-4">
                <span class="far fa-paper-plane"></span>
                </div>
                <h2 class="h5">Email</h2>
                <a href="#">albert931023@gmail.com</a><br>
                <a href="#">91xw24@ms.mingdao.edu.tw</a>
            </div>
        </div>
    </div>
</div>
<div class="col-12 col-lg-8 mt-4 mt-md-0">
<div class="card border-gray-300 p-2 p-md-3 p-lg-5">
    <div class="card-header border-0 bg-white">
        <h3 class="h4">Want to work with us?</h3>
        <p>Cool! Let’s talk about your contribution to the project</p>
    </div>
    <div class="card-body pt-0">
        <form action="#">
            <div class="mb-4">
                <label for="name">Your Name</label>
                <div class="input-group">
                <span class="input-group-text" id="basic-addon3">
                    <span class="fas fa-user-circle">
                    </span>
                </span> 
                <input type="text" class="form-control" placeholder="e.g. Bonnie Green" id="name" required="">
                </div>
            </div>
            <div class="mb-4">
                <label for="email">Your Email</label>
                <div class="input-group">
                <span class="input-group-text" id="basic-addon4">
                    <span class="fas fa-envelope"></span>
                </span> 
                <input type="email" class="form-control" placeholder="example@company.com" id="email" required="">
                </div>
            </div>
            </div>
            <div class="mb-4">
                <label for="message">Your Message</label> 
                <textarea placeholder="Your message" class="form-control" id="message" rows="4" required="" spellcheck="false"></textarea>
            </div>
            <div class="d-grid">
                <button type="submit" class="btn btn-secondary">Send message</button>
            </div>
        </form>
    </div>
</div>
</div>

</main>
{% comment %} <script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAPxf9nr8G8_MLglEt3qRPhACNjA5tbE5o&callback=initMap">
</script> {% endcomment %}
{% endblock %}